blank_issues_enabled: false
contact_links:
  - name: Bestek Discussions
    url: https://github.com/Farmeobaasje/bestek/discussions
    about: Please ask and answer questions here.
  - name: Buy Me a Coffee
    url: https://www.buymeacoffee.com/lynoa
    about: Support the project
